feat: add ci for nightly release
tensorchord/pgvecto.rs pull request #38
Opened 2023-07-31 13:22 UTC by usamoi

Nightly releases will be built on 00:00 UTC+8 if there are any commits in the past 24 hours.

2023-07-31 14:39 UTC, gaocegege submitted a review, later dismissed

2023-07-31 15:12 UTC, VoVAllen requested changes
Please change the trigger to the new tags, and use tag's version as the extension's version.

Example (https://github.com/tensorchord/envd/blob/main/.github/workflows/release.yml):
```yaml
on:
  push:
    tags:
      - 'v*'
``` 
and use `${{ github.event.release.tag_name }}` to get the version


Also better to change the building process to docker instead of pure github action. This makes local debug and build much easier

2023-07-31 15:12 UTC, VoVAllen commented on .github/workflows/release.yml
> +          dpkg-deb --build --root-owner-group ./target/vectors_0.0-0_amd64
We should support dynamic version

2023-07-31 15:12 UTC, VoVAllen commented on .github/workflows/release.yml
> +          echo "Version: 0.0" >> ./target/vectors_0.0-0_amd64/DEBIAN/control
ditto

2023-07-31 15:18 UTC, usamoi commented
@VoVAllen I'm not sure when will the version move from 0.0.0...

2023-07-31 15:21 UTC, VoVAllen commented
@usamoi I already made one https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.1.0. However I think it should be 0.0.1 if we're not confident now. We can start with 0.0.1, it's fine. What do you think?

2023-08-02 01:37 UTC, usamoi commented
r?

2023-08-02 02:32 UTC, gaocegege reviewed
@VoVAllen

2023-08-02 03:09 UTC, VoVAllen approved these changes
Let's merge this first to see whether it works

2023-08-02 03:09 UTC, merged